# Generated by Django 6.0.5 on 2026-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(choices=[('new', 'New'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='NEW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
