# Generated by Django 6.0.5 on 2026-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='NEW'),
        ),
    ]
